### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by jjinsdev** [osahner/ngx-show-hide-password#1]
With ng build, ERROR in Error:  Metadata version mismatch for module "../ngx-show-hide-password/ngx-show-hide-password.d.ts, found version 4, expected 3.

**Comment by osahner** [comment]
Did you try to update the project dependencies (if possible)? 
or even:
```bash
rm -r node_modules
npm install
```
ps: sorry for late, currently in holidays ;)

**Comment by osahner** [comment]
@jjinsdev  If you are still on Angular v4 and can not upgrade to v5, please use the old version `npm i ngx-show-hide-password@1.1.0`.

**Comment by jjinsdev** [comment]
That was it – thank you very much!

Gene Smith
Senior Programmer
Johnson & Johnson, Inc.
PO Box 899
Charleston, SC 29402
843-577-0800 ext 3688
800-487-7565 ext 36.88
