### ISSUE TITLE
error TS2307: Cannot find module '@fortawesome/fontawesome-common-types'.

### ISSUE THREAD

**Issue by baraaAljabali** [osahner/ngx-show-hide-password#10]
I did the installation as instructed on the npm site. It's working all well, but I'm getting this error:
ERROR in node_modules/ngx-show-hide-password/lib/show-hide-password.component.d.ts(32,19): error TS2307: Cannot find module '@fortawesome/fontawesome-common-types'.
node_modules/ngx-show-hide-password/lib/show-hide-password.component.d.ts(33,24): error TS2307: Cannot find module '@fortawesome/fontawesome-common-types'.
how to fix it?

**Comment by osahner** [comment]
Hi @baraaAljabali, may I ask which angular version do you use?

**Comment by baraaAljabali** [comment]
I'm using  version 8.2.14

**Comment by osahner** [comment]
There is a new version from [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome#compatiblity-table) which requires v9. For angular 8 please use 
`yarn add @fortawesome/angular-fontawesome@0.5.0`
I will update the Readme.

**Comment by osahner** [comment]
any news on the issue @baraaAljabali ?
