### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by aymericl** [osahner/ngx-show-hide-password#11]
Hello, 
When I start my application with the commande line "ng serve", I have this error :

 node_modules/ngx-show-hide-password/lib/show-hide-status.directive.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     set showHideStatus(config: ShowHideStatusConfig);

Someone has a solution ? 

Thanks

**Comment by osahner** [comment]
Hi @aymericl 

which version (angular / angular-cli and ngx-show-hide-password)?

**Comment by osahner** [comment]
What I found regarding this issue is https://github.com/microsoft/TypeScript/issues/33939.
Please try using typescript@^3.7

**Comment by danaamiri** [comment]
changing typescript version to 3.7 in angular 8.3 compiler throws error below:
```
ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.7.5 was found instead.
```

**Comment by osahner** [comment]
Ok I see. With angular v8 you should use [ngx-show-hide-password@~2.1.0](/osahner/ngx-show-hide-password#compatibility-chart) and [@fortawesome/angular-fontawesome@^0.5](/FortAwesome/angular-fontawesome#compatiblity-table) 

so please try with following deps:
```shell
yarn add ngx-show-hide-password@~2.1.0
yarn add @fortawesome/angular-fontawesome@^0.5
```

**Comment by osahner** [comment]
@aymericl or @danaamiri any updates? did it work?

**Comment by AleksandrChukhray** [comment]
It's work for me
