### ISSUE TITLE
Change for Angular 10 and fontawesome 0.7

### ISSUE THREAD

**Issue by IngoManthey** [osahner/ngx-show-hide-password#17]
npm WARN ngx-show-hide-password@2.2.4 requires a peer of @angular/common@^9 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-show-hide-password@2.2.4 requires a peer of @angular/core@^9 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-show-hide-password@2.2.4 requires a peer of @fortawesome/angular-fontawesome@^0.6 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-show-hide-password@2.2.4 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

**Comment by osahner** [comment]
I will update the dependencies asap.

**Comment by osahner** [comment]
fixed with ngx-show-hide-password@2.3.0
