### ISSUE TITLE
[ANGULAR 10] An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by mauroprivitera** [osahner/ngx-show-hide-password#18]
Hello, I saw in the past issue this error but with Angular v10 it's seems like different.
Here we are what my terminal says after ng serve.

ERROR in node_modules/ngx-show-hide-password/lib/show-hide-status.directive.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     set showHideStatus(config: ShowHideStatusConfig);

I've already installed :
@fortawesome/fontawesome-common-types

I tried to install also @fortawesome/angular-fontawesome@^0.5 like past issue. 
No changes. Not working yet.

Typescript version 4.0.2.

Thank you for help.

**Comment by osahner** [comment]
Hi @mauroprivitera 

For angular v10 please install @fortawesome/angular-fontawesome@^0.7 => https://github.com/fortawesome/angular-fontawesome#compatibility-table

**Comment by osahner** [comment]
problem solved @mauroprivitera ?

**Comment by mauroprivitera** [comment]
In the end I used Angular 8 for my app, so I can't test again this issue. I think the ploblem was that version by the way.
