### ISSUE TITLE
input-group button falling

### ISSUE THREAD

**Issue by juansesilva** [osahner/ngx-show-hide-password#2]
The input-group button is falling and the size of the input is not 100%
This can be resolved using input-group-btn class instead of input-group-append in the div's button container.
Before:
![eye-before](https://user-images.githubusercontent.com/5069846/37354852-8f28d75a-26b0-11e8-91e9-a3892058954c.png)

After:
![eye-after](https://user-images.githubusercontent.com/5069846/37354871-9ca7c9cc-26b0-11e8-9997-723192e574c1.png)

**Comment by osahner** [comment]
Hi @spiderzelda,

can you please fork this [stackblitz](https://stackblitz.com/edit/angular-okrmdi?embed=1&file=src/app/app.component.html) and show me the error? I fail to reproduce the problem.

**Comment by patrickbard** [comment]
Just installed the latest from npm (2.1.0), and this still occur.
