### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by gloriousjob** [osahner/ngx-show-hide-password#36]
When trying to upgrade my project to Angular 13, this package holds me back due to a peer dependencies error.

>ng update @angular-eslint/schematics  @angular/cli @angular/core 
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 60 dependencies.
Fetching dependency metadata from registry...
                  Package "ngx-show-hide-password" has an incompatible peer dependency to "@angular/common" (requires "^10" (extended), would install "13.1.1").
                  Package "ngx-show-hide-password" has an incompatible peer dependency to "@angular/core" (requires "^10" (extended), would install "13.1.1").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.

** DESIRED OUTCOME **
Project supports Angular 13.
This may be as simple as updating dependencies but not sure if the Ivy requirement will force other changes.

Thanks for your work, @osahner! This package has been simple but effective.

**Comment by osahner** [comment]
Hi @gloriousjob ,
Please try the new beta Version `2.4.0-alpha.1`. 
Will be published asap - later today - as release version `2.4.0`.

**Comment by gloriousjob** [comment]
Thanks! Unfortunately, now it's complaining about base angular packages (the .1 releases never seem to be smooth) after passing your package so I'm not really able to see if this is working. Good enough for me though!
