### ISSUE TITLE
Problem when build

### ISSUE THREAD

**Issue by toshiossada** [osahner/ngx-show-hide-password#4]
I've installed lastest verdion of ngx-show-hide-password and when I import at app.module.ts and try to build project I get the following issue:

![image](https://user-images.githubusercontent.com/2637049/55506597-389eed00-562c-11e9-8fad-dac757eba724.png)

**Comment by osahner** [comment]
Hi @toshiossada,
which angular version do you use?

**Comment by asanka-indrajith** [comment]
I also get this.
angular version 6.0.2.

**Comment by osahner** [comment]
For angular v5/v6 you have to use [ngx-show-hide-password@1.2.6](https://www.npmjs.com/package/ngx-show-hide-password/v/1.2.6) . 
ngx-show-hide-password@^2.0.0 depends on angular v7.
