### ISSUE TITLE
FontAwesome version 6 dependency issue

### ISSUE THREAD

**Issue by gloriousjob** [osahner/ngx-show-hide-password#44]
Hi friend!

I noticed recently that FontAwesome updated to version 6 so I decided to try to update my dependencies in my project. However, when I did so, I got the following:
pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: {projectname}
npm ERR! Found: @fortawesome/free-solid-svg-icons@6.0.0
npm ERR! node_modules/@fortawesome/free-solid-svg-icons
npm ERR!   @fortawesome/free-solid-svg-icons@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @fortawesome/free-solid-svg-icons@"^5" from ngx-show-hide-password@2.4.0
npm ERR! node_modules/ngx-show-hide-password
npm ERR!   ngx-show-hide-password@"^2.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry

It sounds like this project would need to update to fontawesome version 6 if I'm to use any of the newer icons. I'm not sure how you feel about this as I'm guessing some people will try to stay on 5 (although the migration is pretty smooth... they changed icon names but kept aliases so nothing changed in my code).

**Comment by osahner** [comment]
I will - stay tuned

**Comment by osahner** [comment]
fixed with v2.5.0
