### ISSUE TITLE
fontawesome-svg-core 6 issue?

### ISSUE THREAD

**Issue by gloriousjob** [osahner/ngx-show-hide-password#49]
Hi again...

For some reason, even though it looks like 2.6.0 has been updated to support the newer fontawesome, for some reason, I'm hitting an error when I try to update fontawesome svg core. To test, I simply used the following commands:
ng new
npm i @fortawesome/fontawesome-svg-core@6.1.1
npm i ngx-show-hide-password@2.6.0

The last command showed this:
jobbyjohns@Jobbys-Mac-mini b % npm i ngx-show-hide-password@2.6.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: b@0.0.0
npm ERR! Found: @fortawesome/fontawesome-svg-core@6.1.1
npm ERR! node_modules/@fortawesome/fontawesome-svg-core
npm ERR!   @fortawesome/fontawesome-svg-core@"^6.1.1" from the root project
npm ERR!   peer @fortawesome/fontawesome-svg-core@"~1.2.27 || ~1.3.0-beta2 || ^6.1.0" from @fortawesome/angular-fontawesome@0.10.2
npm ERR!   node_modules/@fortawesome/angular-fontawesome
npm ERR!     peer @fortawesome/angular-fontawesome@">=0.7 <1" from ngx-show-hide-password@2.6.0
npm ERR!     node_modules/ngx-show-hide-password
npm ERR!       ngx-show-hide-password@"2.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @fortawesome/fontawesome-svg-core@"^1" from ngx-show-hide-password@2.6.0
npm ERR! node_modules/ngx-show-hide-password
npm ERR!   ngx-show-hide-password@"2.6.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jobbyjohns/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jobbyjohns/.npm/_logs/2022-03-26T04_59_15_410Z-debug-0.log

This is the failure but I'm not sure why since the package.json here expects 6.1.0:
npm ERR! peer @fortawesome/fontawesome-svg-core@"^1" from ngx-show-hide-password@2.6.0
npm ERR! node_modules/ngx-show-hide-password
npm ERR!   ngx-show-hide-password@"2.6.0" from the root project

Any ideas?

**Comment by osahner** [comment]
Hi @gloriousjob 
You are right but it is (_should be_) just a warning. Nevertheless I put a new version `v2.6.1` online. Please give it a try.

**Comment by gloriousjob** [comment]
Thanks friend! The package installs without issues now. As a note, this was preventing my project from building so I appreciate the quick response.
