### ISSUE TITLE
Icon should be swapped

### ISSUE THREAD

**Issue by asanka-indrajith** [osahner/ngx-show-hide-password#5]
Control shows eye icon when password is not revealed and slashed eye icon when password is revealed. Shouldn't it be the other way around?

**Comment by osahner** [comment]
The control icon is an action (button), therefore it shows the goal state and not the state of being.

**Comment by asanka-indrajith** [comment]
Then I think having a feature to toggle default behavior will be great.

**Comment by osahner** [comment]
Actually pretty easy to do with the directives: [stackblitz example](https://stackblitz.com/edit/angular-nakfyr?embed=1&file=src/app/app.component.html&hideExplorer=1). You can customize the control icon as you want, just add `show: 'visibility_off', hide: 'visibility'` to `showHideStatus` options (in case of material design).
