### ISSUE TITLE
[ Question ] - How to apply other styles to this component

### ISSUE THREAD

**Issue by NA-Jalilius** [osahner/ngx-show-hide-password#7]
Hello there @osahner , Hope that you're doing great.
I would like to know if it's possible to apply more styles on this component, I've tried to changed the border color of the button that hold the eye icon with no luck, If you could suggest me a way to do this please !
Thank you in advance friend

**Comment by osahner** [comment]
Hi @NA-Jalilius, 
please take a look at this [example](https://stackblitz.com/edit/angular-dvy758?embed=1&file=src/app/app.component.html). 
Just use the directives & service. If you have any further questions, please ask!
There are some more [basic examples here](https://github.com/osahner/ngx-show-hide-password/tree/master/src/app/app.component.html).

Happy 🎄🎅

**Comment by NA-Jalilius** [comment]
Hello dear @osahner ,

Thanks a lot for your rapid reply, I understand better now.
Thank you so much and Happy New Year to you all 🎉🎉🎄 !

Closing This Issue now [ Question ]
