### ISSUE TITLE
backward compatibility Angular 6

### ISSUE THREAD

**Issue by presercomp** [osahner/ngx-show-hide-password#9]
"ɵɵdefineInjectable" was not found in '@angular/core'. Is necesary change to "defineInjectable" to work

**Comment by osahner** [comment]
Hi @presercomp, for angular 6 please use version 1.2.5.
look over [here : compatibility-chart](https://github.com/osahner/ngx-show-hide-password#compatibility-chart)
`npm i ngx-show-hide-password@1.2.5`

**Comment by presercomp** [comment]
Thanks for you help.
